# Generated by Django 4.2.9 on 2026-02-07 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoardSwiper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryImage', models.ImageField(upload_to='dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProductID', models.IntegerField(blank=True, null=True, unique=True)),
                ('ProductName', models.CharField(blank=True, max_length=255, null=True)),
                ('ProductDescription', models.TextField(blank=True, null=True)),
                ('ProductPrice', models.FloatField(blank=True, max_length=255, null=True)),
                ('ProductImage', models.ImageField(upload_to='dashboard')),
                ('ProductQuantity', models.IntegerField()),
            ],
        ),
    ]
