# Generated by Django 4.2.9 on 2026-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='store.product'),
        ),
    ]
