# Generated by Django 4.2.9 on 2026-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_categories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_products',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_stats',
            field=models.BooleanField(default=False),
        ),
    ]
